export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const ERROR_OCCURRED = "ERROR_OCCURRED";
export const VIEWED_MOVIE = "VIEWED_MOVIE";
export const NOT_VIEWED_MOVIE = "NOT_VIEWED_MOVIE";
export const UPDATE_LOADING = "UPDATE_LOADING";